apiVersion: v1
kind: Pod
metadata:
  labels:
    app: php
  name: php
spec:
  volumes:
    - name: shared-files
      emptyDir: {}
  containers:
    - image: jlamb-php:latest
      name: php
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 9000
      resources:
        limits:
          cpu: "0.1"
      volumeMounts:
        - name: shared-files
          mountPath: /var/www/html
      lifecycle:
        postStart:
          exec:
            command: ["/bin/sh", "-c", "cp -r /app/. /var/www/html"]
